### ISSUE TITLE
Crashes when generating response

### ISSUE THREAD

**Issue by Balkoth** [microsoft/RAG-PDF-Analyzer-WPF-Sample#2]
Something along the lines of: Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: The GPU will not respond to more commands, most likely because of an invalid command passed by the calling application

https://github.com/microsoft/onnxruntime-genai/issues/501

Callstack:
<img width="518" alt="image" src="https://github.com/microsoft/RAG-PDF-Analyzer-WPF-Sample/assets/80055480/b5a0b7b2-facc-4659-a420-da30c78b278b">

Driver:
<img width="269" alt="image" src="https://github.com/microsoft/RAG-PDF-Analyzer-WPF-Sample/assets/80055480/699fb324-0dd5-41ac-8c93-f6f7f3e4c26d">

Windows:
<img width="189" alt="image" src="https://github.com/microsoft/RAG-PDF-Analyzer-WPF-Sample/assets/80055480/cc212041-329a-4130-9c36-f0d326123737">

**Comment by azchohfi** [comment]
I would follow the issue on the onnxruntime-genai repo. There is not much we can do specifically for this sample.
